apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: v2btmy5h2-dotnet-basic-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/v2btmy5h2-dotnet-basic-gitops